#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	enum CHANNELID { SOUND_EFFECT, SOUND_BGM, MAXCHANNEL };

	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO {	INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHA, RENDER_UI, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum MOUSEMOVESTATE {	DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };
	enum RESOBJID {ROCK, TREE, PIG_HOUSE, GRASS, BERRY_BUSH,FIRE_FLIES,TELEPORTER,BOSS_DOOR ,RSOBJ_END};

	enum PLAYERSTATE {
		IDLE, MOVE, BUILD, PICKUP, HIT, ATTACK, FALLDOWN, WAKEUP, EAT, 
		TORCH_IDLE, TORCH_RUN,
		SPEAR_ATTACK,
		PICKING_OBJECT,
		HAMMERING,
		AXE_CHOP_PRE,
		AXE_CHOP_LOOP,
		DEAD,
		STATE_END
	};
	enum LOOKDIR { LOOK_DOWN, LOOK_RIGHT, LOOK_LEFT, LOOK_UP, LOOK_END };
	enum WEAPON { UNARMED, AXE, TORCH, HAMMER, PICK, SPEAR, WEAPON_END }; //플레이어 무기
	enum class eSCENE_TYPE
	{
		LOGO,
		STAGE,
		END
	};

	enum class eLAYER_TYPE
	{
		ENVIRONMENT,
		GAME_LOGIC,
		FORE_GROUND,
		END,
	};
	enum class eOBJECT_GROUPTYPE
	{
		TILE,
		CAMERA,
		BACK_GROUND,
		MOUSE,
		ITEM,
		MONSTER,
		PLAYER,
		RESOURCE_OBJECT,
		OBJECT,
		TRAP,
		UI,
		BOSS,
		EFFECT,
		END = 32,
	};
	enum UI_STATE { UI_STATIC, UI_DYNAMIC, UI_NONE };

	enum TIME_STATE { MORNING, AFTERNOON, NIGHT };

	enum class eCHANNELID
	{
		SOUND_EFFECT,
		SOUND_BTN,
		SOUND_BGM,
		SOUND_ATTACK1,
		SOUND_ATTACK2,
		SOUND_ATTACK3,
		SOUND_ATTACK4,
		SOUND_ATTACK5,
		SOUND_ATTACK6,
		SOUND_ATTACK7,
		SOUND_ATTACK8,
		SOUND_ATTACK9,
		SOUND_ATTACK10,
		SOUND_HIT,
		SOUND_DEAD1,
		SOUND_DEAD2,
		SOUND_DEAD3,
		SOUND_DEAD4,
		SOUND_DEAD5,
		SOUND_DEAD6,
		SOUND_DEAD7,
		SOUND_LDY1,
		SOUND_LDY2,
		SOUND_LDY3,
		SOUND_SELECT,
		SOUND_ENEMY_DEAD,
		SOUND_ENEMY_HIT,
		SOUND_ENEMY_ATTACK,
		SOUND_EFFECT1,
		SOUND_EFFECT2,
		SOUND_EFFECT3,

		MAXCHANNEL,
	};

	enum class eEVENT_TYPE
	{
		CREATE_OBJECT,		// CreateObject
		DELETE_OBJECT,		// DeleteObject
		SCENE_CHANGE,		// SceneChange
		NONE,
	};

	enum  eITEMTOOL_TYPE {
		ITEM_EQUIP,
		ITEM_ALIVE,
		ITEM_WEAPON,
		ITEM_END
	};

	enum UI_ITEM_TYPE { // 인벤/ 생산용인지
		UI_ITEM_INVEN,
		UI_ITEM_CREATE,
		UI_ITEM_END
	};

	enum BOX_TYPE {
		INVEN,
		CREATE,
		BOX_END
	};
	
	enum BOX_DIR { // 나중에 지울것 
		WIDTH,
		HEIGHT,
		BOX_DIR_END
	};

	enum ARMOR_SLOT_TYPE {
		ARMOR = 15,
		HAND,
		HEAD,
		ARMOR_SLOT_END
	};



	enum class eTRAP_STATE
	{
		HIDE,	//숨어있는상태
		GROW,	//나오고있는상태
		MOVE,	//움직이고있는상태
		IDLE,	//나온상태
		HIT,	//부딫힌상태
		DEAD,	//죽은상태
		NONE
	};
}
#endif // Engine_Enum_h__
